### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by ronaldjeden** [groovemonkey/tutorialinux-hashistack#1]
Hi,

Can you add vault to the mix as well? Great tutorial!! Helps me a lot!!!

I had some issues with the SSHGUARD (it did not complete automagically) so installed it manually on the bastion host.

**Comment by groovemonkey** [comment]
Woohoo, thanks for the feedback! And thanks for bringing up the sshguard thing! I think I've fixed it now (some issues with how long AWS instances take to be ready for an apt-get install, I think). Did a TON of updates so the repo should now work with new Terraform versions (and new consul/nomad versions, too).

RE: Vault, I *am* planning on adding it to this repo but it's going to take a while -- first I want to make some videos about consul and nomad, and then deal with the rabbit-hole of configuring vault and consul together in an automated way. Everything gets a lot more complicated to explain once vault is involved (i.e. nomad will have a vault token and spin off per-task tokens that allow an allocation to use vault service roles, consul ACLs will be backed by vault, etc.).

Anyway, it's in the works. Might just take a while.

**Comment by gc-ss** [comment]
Hi!

Seconding this is a great tutorial :tada: 

Noticed that you closed this - does it mean vault support's on a branch already?

**Comment by gc-ss** [comment]
For example, https://github.com/brianshumate/vaultron

This repo already has the tools it needs to get up and running!
